mvp3/mvp/config/routes.rb
Mvp::Application.routes.draw do
  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

   root :to => 'users#index'

end

mvp3/mvp/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  validates_presence_of :email, :partner_email
end

mvp3/mvp/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

mvp3/mvp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

    private

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
end

mvp3/mvp/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:controller =>'users', :notice => 'Login Successful', :action => "show", :id =>current_user.id) }
        format.xml  { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(:users, :notice => 'Goodbye!') }
      format.xml  { head :ok }
    end
  end
end

mvp3/mvp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @users = User.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
         if @user.save
           format.html { redirect_to(:controller =>'users', :notice => 'Login Successful', :action => "show", :id =>@user.id) }
           format.xml  { render :xml => @user, :status => :created, :location => @user }
         else
           format.html { render :action => "new" }
           format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
         end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

mvp3/mvp/app/helpers/application_helper.rb
module ApplicationHelper
end

mvp3/mvp/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

mvp3/mvp/app/helpers/users_helper.rb
module UsersHelper
end

mvp3/mvp/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Sync</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-29070545-1']);
	  _gaq.push(['_setDomainName', 'syncourlives.com']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>

	<div id="header">
		<!-- Login/Sign up -->
		<div id="user_auth">
			<%= link_to "Login", { :controller => 'user_sessions', :action => 'new' }, :class => 'small black login button' -%>
	
			<div class="divider"></div>
			<%= link_to "Sign Up", { :controller => 'users', :action => 'new' }, :class => 'small black signup button' -%>
			        

			<!-- Start Credentials form -->
			<!-- <form id="credentials" method="post" action="">
						    <div class="col">
						    	<input type="text" id="username" value="Email" name="username" tabindex="1"/>
						    </div>
						    <div class="col">
						    	<input type="password" id="password" name="password" value="Password" tabindex="2" maxlength="16"/>
						    	<a href="" class="retrieve_password hide" tabindex="4">Forgot your password?</a>
						    </div>
						</form> <!-- End Credentials form --> -->
			<div class="form_box hide"></div> <!-- Form background -->
		</div> <!-- End user auth -->


 <!-- <div id="header">

				<%= link_to 'Home', users_path %> | 
        <% if current_user %>
        <%= link_to "Edit Profile", edit_user_path(current_user.id)%>
        <%= link_to "Logout", :logout%>
        <% else %>
        <%= link_to "Register", new_user_path%> | 
        <%= link_to "Login", :login %>
        <% end %>
    </div> -->
</div> <!-- Header End -->

<%= yield %>

<div id="footer" class="page"> <!-- Start Footer -->

	<div class="top">
		<img src="/images/logo_footer.jpg" alt="" />
		
		<ul>
			<li class="twitter"><a href="https://twitter.com/#!/synclives">Twitter</a></li>
			<li class="facebook"><a href="http://www.facebook.com/synclives">Facebook</a></li>
			<li class="rss"><a href="http://twitter.com/statuses/user_timeline/479079530.rss">RSS</a></li>
		</ul>
		<div class="clear"></div>
	</div>
	
	<div class="bottom">
		<!--<a href=""><img src="/images/app_store_small.gif" alt="" /></a>-->
		<p>Copyright &copy; 2012 SyncOurLives.com. All Rights Reserved.</p>
		<div class="clear"></div>
	</div>
	
</div> <!-- End Footer -->
</body>
</html>

mvp3/mvp/app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="clear"></div>
	<div id="bottom_content" class="page panes">
	
	<div id="Title" class="Signup">
	<p> Welcome Back! </p> 
	</div>
	<div class="clear"></div>
	<div id="signin_form">
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		</div>
		<div class="actions">
			<%= f.submit "Login" %>
		</div>
	</div>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
<% end %>

mvp3/mvp/app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

mvp3/mvp/app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<>
<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.email %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

mvp3/mvp/app/views/user_sessions/new.html.erb
<div id="top_content_signup" >
	<div id="logo_top">
		<%= link_to "", { :controller => 'users', :action => 'index' }, :id => 'logo-link' -%>
	</div>		
</div>
 <div class="clear"></div>
<%= render 'form' %>

mvp3/mvp/app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user_session.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

mvp3/mvp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	 <div class="clear"></div>

	<div id="bottom_content" class="page panes">
	
			
		 <div id="Title" class="Signup">
			<p> Getting started is a matter of seconds </p> 
		</div>
		 <div class="clear"></div>
		
		<div id="contact" class="pane">
			<div id="contact_form">
				<div class="left">
				  <div class="text_input">
				    <%= f.label :email %><br />
				    <%= f.text_field :email %>
				  </div>
				  <div class="text_input">
				    <%= f.label :password %><br />
				    <%= f.password_field :password %>
				  </div>
				  <div class="text_input">
				    <%= f.label :password_confirmation %><br />
				    <%= f.password_field :password_confirmation %>
				  </div>
				  <div class="text_input">
				    <%= f.label :partner_email %><br />
				    <%= f.text_field :partner_email %>
				  </div>
				  <div class="actions">
				    <%= f.submit "Send" %>
				</div>
			</div> <!-- end left -->
			
			
			<div class="right">
				<div id="reviews"> <!-- Start Reviews -->
					<div class="review">
						<p>Can't wait for the iPhone version. This is awesome even on the web!</p>
						<span>- Esther</span>
					</div>
					<div class="review">
						<p>I love how easy it is to use. No more struggling with texting in a meeting.</p>
						<span>- Billie </span>
					</div>
					<div class="review">
						<p>Now I always know when Aaron's busy.. no more waiting for replies to my messages.</p>
						<span>- Katie </span>
					</div>
					<div class="review">
						<p>Finally.. there is an app for that!</p>
						<span>- Sharon</span>
					</div>
					<!-- Add more reviews here -->
				</div> <!-- End Reviews -->
			</div> <!-- end right -->
			
			<div class="clear"></div>
			
	  </div> <!-- end contact form -->
	</div> <!-- end contact -->
</div> <!-- end bottom content -->
<% end %>

mvp3/mvp/app/views/users/_test.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	 <div class="clear"></div>

	<div id="bottom_content" class="page panes">
	
			
		 <div id="Title" class="Signup">
			<p> Update your profile </p> 
		</div>
		 <div class="clear"></div>
		
		<div id="contact" class="pane">
			<div id="contact_form">
				<div class="left">
				  <div class="text_input">
				    <%= f.label :email %><br />
				    <%= f.text_field :email %>
				  </div>
				  <div class="text_input">
				    <%= f.label :password %><br />
				    <%= f.password_field :password %>
				  </div>
				  <div class="text_input">
				    <%= f.label :password_confirmation %><br />
				    <%= f.password_field :password_confirmation %>
				  </div>
				  <div class="text_input">
				    <%= f.label :name %><br />
				    <%= f.text_field :name %>
				  </div>
				  <div class="text_input">
				    <%= f.label :last_name %><br />
				    <%= f.text_field :last_name %>
				  </div>
				  <div class="text_input">
				    <%= f.label :birthdate %><br />
				    <%= f.date_select :birthdate, :start_year=>1930 , :end_year=>2012 %>
				  </div>
				  <div class="text_input">
				    <%= f.label :partner_email %><br />
				    <%= f.text_field :partner_email %>
				  </div>
				  <div class="text_input">
				    <%= f.label :city %><br />
				    <%= f.text_field :city %>
				  </div>
				  <div class="text_input">
				    <%= f.label :country %><br />
				    <%= f.text_field :country %>
				  </div>
				  <div class="text_input">
				    <%= f.label :share_location %><br />
				    <%= f.check_box :share_location %>
				  </div>
				  <div class="text_input">
				    <%= f.label :mood %><br />
				    <%= f.text_field :mood %>
				  </div>
				  <div class="text_input">
				    <%= f.label :activity %><br />
				    <%= f.text_field :activity %>
				  </div>
				  <div class="actions">
				    <%= f.submit "Send" %>
				</div>
			</div> <!-- end left -->
			
			
		
			
			<div class="clear"></div>
			
	  </div> <!-- end contact form -->
	</div> <!-- end contact -->
</div> <!-- end bottom content -->
<% end %>

mvp3/mvp/app/views/users/edit.html.erb
<div id="top_content_signup" >
	<div id="logo_top">
		<%= link_to "", { :controller => 'users', :action => 'index' }, :id => 'logo-link' -%>
	</div>		
</div>
<div class="clear"></div>

<%= render 'test' %>

<%= link_to 'Back', @user %> |

mvp3/mvp/app/views/users/index.html.erb
<div id="top_content_wrap"> <!-- Start App Description -->
	<div id="top_content" class="page">
		
          <div id="app_screenshot"> <!-- Start App Screencast -->
			<div class="price_badge"></div>
              
              <!-- BEGIN LIKE Button -->
              <iframe src="http://www.facebook.com/plugins/like.php?href=http://www.facebook.com/Synclives"
      scrolling="no" frameborder="0"
      style="border:none; padding-top:300px; padding-left:10px; width:380px; height:70px"></iframe>
   <!-- Like BUTTON END -->
  
           <!---ALTERNATE LIKE:  <div class="fb-like" data-href="http://www.facebook.com/synclives" data-send="false" padding-top="300" padding-left="10" data-width="380" data-show-faces="true" data-action="recommend" data-font="lucida grande"></div> -->
                                      
              
          <!--	<div class="screencast"> 			
                  <iframe src="http://player.vimeo.com/video/14500965?title=0&amp;byline=0&amp;portrait=0" width="195" height="291" frameborder="0"></iframe> 
                  -->
                	<!-- Uncomment to use a static screenshot 
					<img src="images/app_screenshot.jpg" alt="" /> -->
				 <!-- </div> -->
              
		</div> <!-- End App Screencast -->
	
		<div id="app_description"> <!-- Start App Description -->
			<div class="header">
				<a href="#"><h1>Sync</h1></a>
				<!-- <div class="version">NEW RELEASE</div> -->
				<div class="clear"></div>
			</div>

							

			<p>We are building tools for couples to <b>seamlessly share</b> lives with each other in a 
             <b>private space</b> with a <b>single click</b> and make dating more fun</p>				

			<ul>
				<li>Share easily, directly and privately. Share with fun!</li>
				<li>See your life together in one beautiful space</li>
		
			</ul>
		    
		   
			<div class="actions">
				
<a href="https://testflightapp.com/join/4939f13e943fd2d9c57f004e8fa67f78-NTc5Njg/" class="app_store"> Beta available on TestFlight</a>
					<p>
						<b>Download over your iPhone</b>
						Create an account in seconds and login to invite your partner!
					</p>
					<div class="clear"></div>
			</div>
		
		</div> <!-- End App Description -->
		<div class="clear"></div>
	</div>
</div>

<div id="page_seperator"></div>

<div id="nav"> <!-- Start Page Navigation -->
	<ul class="tabs page">
		<li><a href="#home">Home</a></li>
		<li><a href="#about">About</a></li>
		<li><a href="#screenshots">Screenshots</a></li>
		<li><a href="#release_notes">Privacy Policy</a></li>
		<li><a href="#contact">Contact</a></li>
	</ul>
	<div class="clear"></div>
</div> <!-- End Page Navigation -->
 
<div id="bottom_content" class="page panes">
	
	<div id="home" class="pane"> <!-- Start Homepage -->
		
		<div id="features"> <!-- Start Features -->
			<div class="feature">
				<div class="new"></div>
				<div class="content">
					<div class="screenshot">
						<img src="images/feature_1.jpg" alt="" />
						<a href="images/feature_1.jpg" class="screenshots" rel="group">Enlarge</a>
					</div>
					<p>Share your location whenever you wish with a single click! See where your love is!</p>
				</div>				
				<div class="bottom"></div>
			</div>
			<div class="feature">
				<div class="content">
					<div class="screenshot">
						<img src="images/feature_2.jpg" alt="" />
						<a href="images/feature_2.jpg" class="screenshots" rel="group">Enlarge</a>
					</div>
					<p>Status buttons let you be considerate! Let her know when you are away and busy!</p>
				</div>				
				<div class="bottom"></div>
			</div>
			<div class="feature last">
				<div class="content">
					<div class="screenshot">
						<img src="images/feature_3.jpg" alt="" />
						<a href="images/feature_3.jpg" class="screenshots" rel="group">Enlarge</a>
					</div>
					<p>Couples need their special emoticons! A special app for him and her to share them: smooches and winks by Sync.</p>
				</div>				
				<div class="bottom"></div>
			</div>
			<div class="clear"></div>
		</div> <!-- End Features -->
	
		<div id="reviews_faqs">
		
			<div id="reviews"> <!-- Start Reviews -->
				<div class="review">
					<p>Can't wait for the iPhone version. This is awesome even on the web!</p>
					<span>- Esther</span>
				</div>
				<div class="review">
					<p>I love how easy it is to use. No more struggling with texting in a meeting.</p>
					<span>- Billie </span>
				</div>
				<div class="review">
					<p>Now I always know when Aaron's busy.. no more waiting for replies to my messages.</p>
					<span>- Katie </span>
				</div>
				<div class="review">
					<p>Finally.. there is an app for that!</p>
					<span>- Sharon</span>
				</div>
				<!-- Add more reviews here -->
			</div> <!-- End Reviews -->
		
			<div id="faqs"> <!-- Start FAQs -->
				<div class="left_column">
					<div class="faq">
						<b>Who is this for?</b>
						<p>Sync is for couples. Particularly those who are in long distance relationships and need an easy way to share their busy lives with each other.</p>
					</div>
				
					<div class="faq">
						<b>Is my data safe?</b>
						<p>Unlike social networks, we respect your privacy and right to own your pictures and conversations. We claim no rights to any of them.</p>
					</div>
				</div>
			
				<div class="right_column">
					<div class="faq">
						<b>What if I need more features?</b>
						<p>We are working on it! Meanwhile, tell us what you would like.</p>
					</div>
				
					<div class="faq">
						<b>When's the iPhone app coming?</b>
						<p>Soon. Meanwhile, we would love to have your feedback on our web app!</p>
					</div>
				</div>
				<div class="clear"></div>
			</div> <!-- End FAQs -->
		
			<div class="clear"></div>
		
		</div>
	</div> <!-- End Homepage -->
	
	<div id="about" class="pane"> <!-- Start About Page -->
		<div class="left">
			<h2>We are Sync</h2>
			<p>We are a group of Stanford students dedicated to the mission of building healthier relationships. The fast-paced world around us and proliferating social networks often make us neglect the one most important relationship in our lives - our partner. The eye-witness to your life needs help keeping in sync with your world, especially when you are traveling or living apart.</p>
			
			<p>With this noble purpose, we are building Sync. This is our alpha version and we hope to use our research to bring better, more useful apps to you that will make  apositive difference in your life and that of your loved one.</p>
		</div>

		<!-- <div class="right">
					<h2>The Team</h2>
					
				</div> -->
		<div class="clear"></div>
	</div> <!-- End About Page -->
	
	<div id="screenshots" class="pane"> <!-- Start Screenshots Page -->
		<!--<h2>App Screenshot</h2> -->
          <img src="images/coming_soon.png" alt=""/>
		  <div class="clear"></div>
	</div> 
     

          <!---
          <ul>
			<li><a href="images/screenshot_1.jpg" class="screenshots" rel="group_1"><img src="images/screenshot_1.jpg" alt="" /></a></li>
			<li><a href="images/screenshot_2.jpg" class="screenshots" rel="group_1"><img src="images/screenshot_2.jpg" alt="" /></a></li>
			<li><a href="images/screenshot_3.jpg" class="screenshots" rel="group_1"><img src="images/screenshot_3.jpg" alt="" /></a></li>
			<li><a href="images/screenshot_4.jpg" class="screenshots" rel="group_1"><img src="images/screenshot_4.jpg" alt="" /></a></li>
		</ul> -->
          
		        <!-- End Screenshots Page -->
	 
	<div id="release_notes" class="pane"> <!-- Start Release Notes Page -->
		<div class="release"> <!-- Start Release -->
			<div class="left">
				<h3>Privacy Policy</h3>
				<span class="date">Policy released 02/01/12</span>
			</div>
			<div class="right">
				<ul>
					<li>All your data is private. We do not own it and have no rights to it.</li>
					<li>Unlike social networks, we take your privacy and your relationships seriously. They are paramount to us. Access to your data will be fully controlled at each step by you.</li>
					
				</ul>
			</div>
			<div class="clear"></div>
		</div> 
      </div>
            <!-- End Release --> <!-- Start Release Notes Page -->
		
          <!--
          <div class="release">
			<div class="left">
				<h3>SlickApp 1.2</h3>
				<span class="date">Released on 9/15/10</span>
			</div>
			<div class="right"></div>
			<div class="clear"></div>
		</div>
          
		<div class="release last">
			<div class="left">
				<h3>SlickApp 1.1</h3>
				<span class="date">Released on 08/20/10</span>
			</div>
			<div class="right">
			</div>
			<div class="clear"></div>
		</div> 
              --->
          
          <div id="contact" class="pane"> <!-- Start Contact Page -->
		<div id="contact_form">
			<div class="left">
				<form action="javascript:;" method="post"> <!-- Start Contact Form -->
					<p>
						<label>Name</label>
						<input type="text" id="name" name="name" class="text_input" />
					</p>
					<p>
						<label>Email</label>
						<input type="text" id="email" name="email" class="text_input" />
					</p>
					<p>
						<label>Subject</label>
						<select id="topic" name="topic" class="text_input">
							<option value="General Support">General Support</option>
							<option value="Bug Report">Bug Report</option>
						</select>
					</p>
					<p>
						<label style="height: 105px">Message</label>
						<textarea id="message" name="message" class="text_input" rows="" cols=""></textarea>
					</p>
					<p class="validation">All Fields Are Required</p>
					<input type="image" src="images/send.gif" class="send" id="send" />
				</form> <!-- End Contact Form -->
			</div>
			
			<div class="right">
				<b>Get In Touch</b>
				<p>Please reach out to us, we would love to hear about your inputs, pain points and experiences.</p>
				<a href="" class="email">founders@syncourlives.com</a> <!-- Add your email here -->
			</div>
			
			<div class="clear"></div>
		</div>
	</div> <!-- End Contact Page -->
	<!-- Start Facebook Platform "Like script" -->
	    <div id="fb-root"></div> 
	        <script>(function(d, s, id){
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
	    <div class="fb-like"></div>
	<!-- End Facebook "Like script" -->
</div>

mvp3/mvp/app/views/users/new.html.erb
<div id="top_content_signup" >
	<div id="logo_top">
		<%= link_to "", { :controller => 'users', :action => 'index' }, :id => 'logo-link' -%>
	</div>		
</div>
 <div class="clear"></div>
<%= render 'form' %>

mvp3/mvp/app/views/users/show.html.erb
<div id="top_content_signup" >
	<div id="logo_top">
		<%= link_to "", { :controller => 'users', :action => 'index' }, :id => 'logo-link' -%>
	</div>		
</div>
<div class="clear"></div>
<p id="notice"><%= notice %></p>

<div id="bottom_content" class="page panes">
	<div id="Title" class="Signup">
		<p> About your partner</p> 
	</div>
	<br>
	<br>
	<br>
	<div id="left">
		
		<!-- After login, display partner's data -->
		<% if current_user%>
			<br>
				<% @users.each do |u| %>
					<% if u.email == current_user.partner_email %>
						
							<p>
							  Your Partner: <b> <%= u.name %> <%= u.last_name %></b>
							</p>

							<p>
							  Is currently <b><%= u.activity %></b>
							</p>
							
							<p>
							  And feeling <b><%= u.mood %> </b>
							</p>
					<% end %>
				<% end %>
			</p>
		<%end%>

	<div>
</div>
<br>
<%= link_to 'Edit your profile', edit_user_path(@user) %> 
<!-- <%= link_to 'Back', users_path %> -->